### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by hanshopkins** [mirochaj/ares#52]
Hi, I notice that when running many simulations in a loop, Python garbage collection does not clear memory. This is the minimal reproducible example.  [memory_leak_min_rep_ex.txt](https://github.com/mirochaj/ares/files/9284602/memory_leak_min_rep_ex.txt)

If you look at the consumed ram with top, it increases with each loop by more than you would expect from saving to the numpy array. The expected behaviour is that all memory that ARES is consuming should be freed after each loop.

**Comment by mirochaj** [comment]
Hi Hans, have you tried calling the garbage collector explicitly? I would recommend that at the end of each iteration of the loop, you do `del sim; gc.collect()` after doing `import gc` at the top of your script. The simulation object carries a lot more info than just the dTb array, which is why the steps you're seeing are much bigger than expected.

**Comment by hanshopkins** [comment]
Hi Jordan,

I just tested it, and calling the garbage collection explicitly does free up the memory! So all of the other stuff that the sim object saves doesn't get cleared automatically when the sim object is deleted. Thanks for pointing that out.
