### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by htjb** [mirochaj/ares#62]
In the tagged versions of the code is it possible to change the version numbers in the `setup.py` file? Same for the main branch? At least for the main branch of the code and for the tagged version `v0.9` the versions in `setup.py` are both 0.1. Therefore, running `pip install .` or equivalently `python setup.py install` on both branches appears to install the same version of the code e.g. running `pip show ares` returns version 0.1.

This makes version control quite difficult e.g. making sure I'm running the same version of `ares` on different machines.

**Comment by mirochaj** [comment]
Hi @htjb, this is a good question, though I'm afraid I don't have a quick fix. I agree it'd be great if there was consistency between versions listed in the source code (setup.py and various files in the docs) and the actual git version (hash or tag). A quick google search revealed a few options for automating consistency here, some that would require including another dependency that takes care of this sort of thing, and some homegrown solutions that I still need to digest. It'd be great to try to improve this so I'll keep this issue open and try to keep reading up on how people handle this.

In the meantime, one thing I do have implemented is a simple function that will retrieve the git hash of the current ARES version. Hopefully the following works:

`ares.util.Misc.get_hash()`

I will sometimes store that string in output files so that I can check later if something has been broken. I think this routine could be modified or augmented to report a tag if one exists.

Sorry to not be more helpful, will try to circle back to this soon. In the meantime do let me know if any solutions seem particularly appealing/easy.

**Comment by htjb** [comment]
@mirochaj thanks for the quick reply! Perhaps it's not possible to change a file on a tagged branch but maybe in the future e.g. for #61 the version number could be included in the `setup.py`?

Ohh wow that `get_hash()` code is very cool! I will check that out, thanks.

A colleague implemented version increment and release workflows (https://github.com/htjb/globalemu/pull/16) for my `globalemu` code. The workflow basically blocks pull requests if the version hasn't been bumped and makes a release (equivalent of your tagged versions I think) with the version number when the PR goes through. Seemed to work really well and I think a few other colleagues have adopted it for their code bases as well.

**Comment by mirochaj** [comment]
Thanks for passing that along, I'll take a look.
